name: Run Hello Action
on: push
jobs:
    hello:
        runs-on: ubuntu-latest
        name: Hello
        steps:
            - name: Hello
              uses: shunya-sunaba/3-hello-action-master@v1.0.0
